#!/usr/bin/env ruby

# Prevents a commit if any image URLs are missing.

# To enable this hook, run the following in this repo locally:
#   git config --local core.hooksPath .githooks

file = "README.md"
stdout = `git status -s | grep "^M  #{file}"`
readme_staged = !stdout.empty?
exit 0 unless readme_staged

pattern = /^\s*- ((?<!\*\*)[^\[])*\[((?! \]|->\n|github.com).)+$/
contents_after_toc = File.read(file).sub(/.+## Table of contents.+?(?=##)/m, "")
lines = contents_after_toc.split("\n").map { _1 << "\n" }

red = "\x1b[1;31m"
dim = "\x1b[2m"
reset = "\x1b[0m"

bad_lines = lines.filter_map.with_index { |line, index|
  if pattern.match?(line)
    "#{file}:#{index + 1} #{dim}#{line.lstrip}#{reset}"
  end
}

if bad_lines.any?
  puts "\n#{red}Oops! Missing image URLs:#{reset} \n\n" + bad_lines.join
  exit 1
end

exit 0
