#!/usr/bin/env ruby

# Prevents a commit if any image URLs are missing.

# To enable this hook, run the following in this repo locally:
#   git config --local core.hooksPath .githooks

file = "README.md"

pattern = /^\s*- ((?<!\*\*)[^\[])*\[((?! \]|->\n|github.com).)+$/
content_before_toc_end, content_after_toc = File.read(file).partition(/.+## Table of contents.+?(?=##)/m)[1..2]
line_count_before_toc_end = content_before_toc_end.count("\n")
lines = content_after_toc.split("\n").map { it << "\n" }

red = "\x1b[1;31m"
dim = "\x1b[2m"
reset = "\x1b[0m"

bad_lines = lines.filter_map.with_index { |line, index|
  if pattern.match?(line)
    "#{file}:#{index + 1 + line_count_before_toc_end} #{dim}#{line.lstrip}#{reset}"
  end
}

if bad_lines.any?
  puts "\n#{red}Oops! Missing image URLs:#{reset} \n\n" + bad_lines.join
  `git reset`
  exit 1
end

exit 0
